### ISSUE TITLE
Location Flag for Result = 0

### ISSUE THREAD

**Issue by WebMDT-Marco** [blackdotsh/getIPIntel#13]
I may be answering my own question, but when an IP returns a result of 0, the Location is set to NULL (when viewing in JSON format) or doesn't return anything (when viewing normally).

Is this by design, or a glitch ? As in, is it assumed that a GOOD IP the end-user really doesn't need to see the location.

Thank you for all you do and your  great platform

**Comment by blackdotsh** [comment]
Can you email me or DM me on twitter the IP address so I can look into the issue? GeoIP is still in alpha.

**Comment by WebMDT-Marco** [comment]
Sorry for the delayed response, my notifications weren't setup properly.

In the test setup this issue seems to have gone away with the IP's it was occurring on. If it arises again I'll send you the IPs.
