### ISSUE TITLE
Cloudflare IP's are getting caught in VPN filter

### ISSUE THREAD

**Issue by Newcool1230** [blackdotsh/getIPIntel#15]
Hello,

I have Cloudflare to protect my website from DDOS attacks. If I use the PHP Proxy Detection API, it will only detect Cloudflare IP's.

Do you have a proper way to bypass this, so I can implement it on my website?

Regards,
Mike

**Comment by blackdotsh** [comment]
If you look at Cloudflare's documentation:

https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-

> CF-Connecting-IP
> 
> To provide the client (visitor) IP address for every request to the origin, Cloudflare adds the CF-Connecting-IP header.
> 
> "CF-Connecting-IP: A.B.C.D"
> 
> Where A.B.C.D is the client's IP address, also known as the original visitor IP address.
> 

So instead of  `$ip=$_SERVER['REMOTE_ADDR'];`

you would use `$ip=$_SERVER["HTTP_CF_CONNECTING_IP"];`
