### ISSUE TITLE
Returning the response code value = 0

### ISSUE THREAD

**Issue by Sriyank** [blackdotsh/getIPIntel#18]
I am using this API to kick players who join with VPN to my SAMP Game Server.
usually response code = 200 means OK but I am getting response code 0 and it is kicking all the players.
Please help me.

**Comment by blackdotsh** [comment]
The API should never return HTTP "0" as the response. The server can return HTTP 200, HTTP 429 if you exceed the 15 queries per limit on the free API, or HTTP 400 if you exceed the daily query limit. Please email me and let me know either the contact email or the IP you're using to query the API.

**Comment by Sriyank** [comment]
It was response code 1 and btw thanks, fixed it.
