### ISSUE TITLE
Can I get any information on why I might have been banned?

### ISSUE THREAD

**Issue by smokenmirrors2** [blackdotsh/getIPIntel#6]
I keep getting a response of -5, server IP is 103.196.240.207

Thanks! I really love your service, don't know if I exceeded the rate limit... or I was testing with a fake email? I don't know but I understand why you want a contact email so we don't keep sending requests if it might be broken.

**Comment by blackdotsh** [comment]
Hi,

Please delete this issue as you're exposing your server's IP address. Contact me privately via email or twitter DM and I'll respond ASAP.
