### ISSUE TITLE
Are you implying that all users of VPN connections are malicious?

### ISSUE THREAD

**Issue by magicgoose** [blackdotsh/getIPIntel#8]
There are legitimate reasons for normal people to use VPN or Tor, especially in countries who do too much surveillance.  
The README seems to say that all these people are trolls, bots, etc.

This does not make sense.

**Comment by blackdotsh** [comment]
There are definitely legitimate uses for VPN or TOR. Not all VPN / TOR traffic is bad. Most sites serving most traffic do not need to use this service.

However, there are many instances where site administrators simply get too much malicious traffic from these IPs. People tend to abuse online advertising sites, referral systems, check out systems, etc.

It's up to the site admin to say what they want to allow or not, this is a tool that site admins can choose to use. I don't actively advertise this service as there's no advertising budget. The people that use this service are actively seeking it.

In addition, a VPN user can always contact the site administrator directly and explain their situation. It would again, be up to the site administrator to allow that person or not.
